### ISSUE TITLE
Getting prices in EUR

### ISSUE THREAD

**Issue by duarteocarmo** [LunaticMuch/msdownloader#1]
Hey! Love your script! Any idea on how I can get the price of a fund in EUR? 

In [this ETF](https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx?id=0P0001LBAG&ClientFund=0&LanguageId=da-DK&CurrencyId=DKK&UniverseId=ETEXG%24XETR&BaseCurrencyId=EUR) for example. How would I go about it? 

I can script it myself, just need some tips on the API 😄

**Comment by LunaticMuch** [comment]
That fund is officially traded in USD. You see it on the [manager website](https://www.vaneck.com/nl/en/etf/equity/smh/overview?country=nl&audience=retail) and the same appears when you dump it

```json
        "TradingCurrency": {
            "Id": "USD"
        }
```

now the question is how it comes to EUR. I guess I can ask the API to dump it Euro. 
Although, this would applied the predefined USD/EUR evaluation decided by MS. I generally track investment in the currency they are officially traded and apply my conversion if I really want to see in a different currency.
Let me check anyway how to make it happen.

**Comment by duarteocarmo** [comment]
Some funds I track are usually from the XETRA exchange, which means they are traded in EUR officially (as far as I know). Good example  [here](https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx?id=0P0000ZVS0)


Really appreciate the help! Really tired of scraping from different sources, this would definitely improve [my workflow](https://duarteocarmo.com/blog/hacking-on-my-finances.html)

**Comment by LunaticMuch** [comment]
I see. Technically, it's a bit complex, the funds is issued and evaluated under a single currency (USD in your case), however it can be traded with a market currency.
My approach, which uses an ISIN, is not the best as a security (ETF, fund, share), can have a the same ISIN across all markets. The Sedol or WKN (as you're on XETRA) is instead unique; unfortunately not many people can get it. It's not hidden or secret but nothing you normally see in bold.

Your fund must be retrieve specifically from Xetra as otherwise it comes from standard market. I've found it and can get it out, need to make few changes, but good you brought the problem.

```json
    {
        "_Id": "0P0001LBAG",
        "ISIN": "IE00BMC38736",
        "Name": "VanEck Vectors Semiconductor ETF EUR",
        "wkn": "A2QC5J",
        "Ticker": "VVSM",
        "ClosePriceDate": "2021-01-15",
        "ClosePrice": 18.776,
        "PriceCurrency": "EUR"
    }
```

**Comment by duarteocarmo** [comment]
Completely fair, probably I'm an exception, not sure. But in the EU, these are the most types of funds we're exposed to. Right now, I have a super rudimentar scrapper of these pages, that extracts the summarized value directly.

But you're API approach looks much more robust. Let me know if I can help!

And thanks for an awesome project!

**Comment by LunaticMuch** [comment]
@duarteocarmo if you can download the version on the branch called `ms-universe` you can have a test. The problem is not about prices in EUR, rather it's about the _universe_ concept. Morningstar applies the concept of universe to subset markets and/or type of products. As your ETF is not in the default universe you must specify one to get it. 
This brought me to radically change the yaml format in order to specify the universe and the name per security. The README should be straightforward to follow and the `security_example.yaml` contains your ETF as an example. I can download that data.
I need to make a couple of more checks for shares now, but if you just need ETF and funds you're good to go. 
As I made a quick fix, I used `pydash` for a quick function, so please update the requirements on your local as well.

**Comment by duarteocarmo** [comment]
Hey @LunaticMuch! Sorry for the delayed reply - been crazy at work. 

Thanks so much for this! I cloned and wanted to start testing but noticed that in the `security_example.yaml` you require a `universe` parameter. What is it? And how can I find it from a fund page? 

Example, where can I find the universe parameter of [this ](https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx?id=0P0000ZVS0)fund?

**Comment by LunaticMuch** [comment]
@duarteocarmo yeah you need it for the ETF you provided. Check the new README in the branch, it should explain it (it's a good way for me to crosscheck the readme makes sense :D )

**Comment by duarteocarmo** [comment]
Huumm. 

I checked the readme, but I can't find such parameter in the [url I am visiting](https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx?id=0P0000ZVS0).. The fund page that you link in the readme looks very different from the one I am seeing.. 

Wonder if there is a solution?

**Comment by LunaticMuch** [comment]
This is interesting, cause it should come in the URL and it was included in the URL you published when you opened the issue

```
https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx
?id=0P0001LBAG
&ClientFund=0
&LanguageId=da-DK
&CurrencyId=DKK
&UniverseId=ETEXG%24XETR
&BaseCurrencyId=EUR
```

I am wondering how did you copy it now

**Comment by duarteocarmo** [comment]
All I see in the link is:
```bash
https://www.morningstar.dk/dk/etf/snapshot/snapshot.aspx?id=0P0000Y16J
```

Weirdly 🤔

**Comment by LunaticMuch** [comment]
short answer is use `ETEXG$XETR` as universe. Long answer: I think I need to provide a list of universe, there's a meaning in that string. It should also work with `ETEXG$$ALL`

**Comment by duarteocarmo** [comment]
That worked perfectly!!!! Thanks so much!! Won't bother you anymore  😄

**Comment by LunaticMuch** [comment]
Ok, I am going to merge back into main, so to keep align switch to the main branch.
